SELECT * FROM PRODUCT  WHERE PRODUCTID=1;

INSERT INTO PRODUCT (PRODUCTID, P_NAME, P_PRICE, P_DESC, VENDORID)
VALUES (2, 'DONUT', 1.5, 'LEMBUT', 1);

INSERT INTO PRODUCT (PRODUCTID, P_NAME, P_PRICE, P_DESC, VENDORID)
VALUES (3, 'KUIH PELITA', 2.5, 'MANIS', 1);

INSERT INTO PRODUCT (PRODUCTID, P_NAME, P_PRICE, P_DESC, VENDORID)
VALUES (4, 'SATAY', 10.5, 'LAPAR', 1);

INSERT INTO PRODUCT (PRODUCTID, P_NAME, P_PRICE, P_DESC, VENDORID)
VALUES (5, 'LEMANG', 5.0, 'MAHAL', 1);

INSERT INTO FOOD (FOODID, PRODUCTID, F_SPICYLEVEL)
VALUES (3, 2, 'ORIGINAL');

INSERT INTO FOOD (FOODID, PRODUCTID, F_SPICYLEVEL)
VALUES (2, 3, 'ORIGINAL');

INSERT INTO FOOD (FOODID, PRODUCTID, F_SPICYLEVEL)
VALUES (22, 4, 'MILD');

INSERT INTO FOOD (FOODID, PRODUCTID, F_SPICYLEVEL)
VALUES (23, 5, 'ORIGINAL');

COMMIT;

SELECT * FROM PRODUCT P JOIN FOOD F ON P.PRODUCTID=F.PRODUCTID;

SELECT * FROM PRODUCT  WHERE productid=1;